# Generated by Django 5.1 on 2024-08-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='habilidades',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='interesses',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
