# Generated by Django 5.1 on 2024-08-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_foto_aluno_habilidades_aluno_interesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
